package cz.komix.qsystem.backend.logic.isaaaquery;

/**
 * Require ability to deserialize IS AAAA string response into
 * object generated by XJC (e.g. {@link StandardQueryResponseData}) - generated based on isaaa-interface-contract/query/response
 *
 * @author Jan Lejnar
 */
public interface IDeserializeToResponseData {
    StandardQueryResponseData deserializeStandardQuery(String serializedResponse);

    ComplementQueryResponseData deserializeComplementQuery(String serializedResponse);
}
