package cz.komix.qsystem.backend.logic.isaaaquery;

/**
 * Require ability to serialize object generated by wsimport (e.g. {@link StandardQueryType}) - generated based on isaaa-interface-contract/query/wsdl
 * into IS AAAA string request.
 *
 * @author Jan Lejnar
 */
public interface ISerializeRequestData {
    String serializeStandardQueryRequestData(StandardQueryType searchCriteria);

    String serializeComplementQueryRequestData(AAAIDType AAAID, SubsetCriteriaType subsetCriteriaType);
}
